### ISSUE TITLE
Moodle 1.9 as remote?

### ISSUE THREAD

**Issue by klorinczi** [LafColITS/moodle-local_remote_backup_provider#10]
Could be possible to use Moodle 1.9 as remote?

**Comment by mackensen** [comment]
Web services look completely different in Moodle 1.9 and are much less capable. The backup system is different as well. It would have to be a separate plugin. It's not something I'm planning to work on as my institution no longer supports Moodle 1.9.

**Comment by klorinczi** [comment]
Thanks for your answer.

I would develop it, but I have no experience with web services. Except the web services I could develop the plugin.

I suppose I need to trigger to start backup function for the specific course, then transfer the backup file to the target Moodle (3.x).

Moodle 1.9 has XML-RPC support, has MNET support, and using OK Tech plugin has REST support.
Any of them would allow to trigger execution of remote functions.

The question is, how should I do to trigger execution of the backup script. 
Also how to retrieve the backup file from source Moodle 1.9 to target Moodle 3.x?
